✨ Update to v3.3.2 (#51)
## v3.3.2, 2021-05-01

### 🔴 Виправлення помилок

#### ENG🇬🇧

- виправлено помилку `nlp.max_length limit exceeded`:
  Text of length 1195652 exceeds maximum of 1000000. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the nlp.max_length limit. The limit is in number of characters, so you can check whether your inputs are too long by checking len(text).
  Встановлено ліміт `NLP_EN.max_length = 5000000`;
- виправлено помилку `ImportError: cannot import name 'escape' from 'jinja2'`:
  This happens because Jinja has removed those functions in a recent version —  3.1.0 — [released on March 24th, 2022](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0).

  > ``Markup`` and ``escape`` should be imported from MarkupSafe.

  You have two options form here:
  1. either this error comes from one of your dependency.
    The first thing you should consider is to upgrade the said dependence(s). If this is not possible, what you can do, from here is to downgrade your Jinja version to a version that would still include `escape`, for example, adding it explicitly in your _requirements.txt_:
    
    ```
    jinja2<3.1.0
    ```
  2. or, your error is from code you wrote, so you can fix it by importing it from MarkupSafe, as suggested in the Jinja release notes.
    
    So, you should use
    ```python
    from markupsafe import escape
    ```
    instead of 
    ```python
    from jinja2 import escape
    ```
  При використанні `Flask==1.1.2` треба зафікмувати наступні залежності: `jinja2<3.1.0`; `itsdangerous==2.0.1`, `Werkzeug<2.0.0`;
- дрібні виправлення коду.

### ⚠️ Зауваження

#### ENG🇬🇧

- оновлено бібліотеку spaCy до версії `3.0.6`;
- встановлено `keepalive_timeout   1050` для nginx;

-----

* fix fetch of parce.xml

* update to v3.3.1

- update to v3.3.1

* update spaCy up to `3.0.6`

update spaCy up to `3.0.6`

* V3/feature/fix text max length and version update 3 0 8 (#50)

* update spaCy up to `3.0.8`;

update spaCy up to `3.0.8`;

* Fix maximum Text of length of nlp

Fix Text of length nlp exceeds maximum of 1000000. Set nlp up to `NLP_EN.max_length = 2000000`

* cleanup

* update and fix Flask

fix `ImportError: cannot import name 'escape' from 'jinja2`:

Jinja is a dependency of Flask and Flask V1.X.X uses the escape module from Jinja, however recently support for the escape module was dropped in newer versions of Jinja.

To fix this issue, simply update to the newer version of Flask V2.X.X in your requirements.txt where Flask no longer uses the escape module from Jinja.

Flask==2.1.2

* set spacy to 3.0.6

* revert spacy to 3.0.8

revert spacy to 3.0.8

* update spaCy up to `3.1.6`

update spaCy up to `3.1.6`

* Set Flask to 2.0.3

Set Flask to 2.0.3

* Set Flask==1.1.2

Set Flask==1.1.2

* Set jinja2<3.1.0

Set jinja2<3.1.0

* Set itsdangerous==2.0.1

Set itsdangerous==2.0.1

* Cleanup

Cleanup

* Set Werkzeug < 2.0.0

Set Werkzeug < 2.0.0

* Set spacy to 3.0.8

Set spacy to 3.0.8

* Set spacy to 3.0.6

Set spacy to 3.0.6

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Set NLP_EN.max_length = 5000000

Set NLP_EN.max_length = 5000000

* Set keepalive_timeout   1550

Set keepalive_timeout   1550

* add big test file for en

add big test file for en

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Update to v3.3.2

Update to v3.3.2