Fix Readme (#58)
* fix fetch of parce.xml

* update to v3.3.1

- update to v3.3.1

* update spaCy up to `3.0.6`

update spaCy up to `3.0.6`

* V3/feature/fix text max length and version update 3 0 8 (#50)

* update spaCy up to `3.0.8`;

update spaCy up to `3.0.8`;

* Fix maximum Text of length of nlp

Fix Text of length nlp exceeds maximum of 1000000. Set nlp up to `NLP_EN.max_length = 2000000`

* cleanup

* update and fix Flask

fix `ImportError: cannot import name 'escape' from 'jinja2`:

Jinja is a dependency of Flask and Flask V1.X.X uses the escape module from Jinja, however recently support for the escape module was dropped in newer versions of Jinja.

To fix this issue, simply update to the newer version of Flask V2.X.X in your requirements.txt where Flask no longer uses the escape module from Jinja.

Flask==2.1.2

* set spacy to 3.0.6

* revert spacy to 3.0.8

revert spacy to 3.0.8

* update spaCy up to `3.1.6`

update spaCy up to `3.1.6`

* Set Flask to 2.0.3

Set Flask to 2.0.3

* Set Flask==1.1.2

Set Flask==1.1.2

* Set jinja2<3.1.0

Set jinja2<3.1.0

* Set itsdangerous==2.0.1

Set itsdangerous==2.0.1

* Cleanup

Cleanup

* Set Werkzeug < 2.0.0

Set Werkzeug < 2.0.0

* Set spacy to 3.0.8

Set spacy to 3.0.8

* Set spacy to 3.0.6

Set spacy to 3.0.6

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Set NLP_EN.max_length = 5000000

Set NLP_EN.max_length = 5000000

* Set keepalive_timeout   1550

Set keepalive_timeout   1550

* add big test file for en

add big test file for en

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Update to v3.3.2

Update to v3.3.2

* Fix UkrVectōrēs app website address

Fix UkrVectōrēs app website address to https://konspekt.ai-service.pp.ua

* Add license 1 (#53)

* V3/develop (#52)

* fix fetch of parce.xml

* update to v3.3.1

- update to v3.3.1

* update spaCy up to `3.0.6`

update spaCy up to `3.0.6`

* V3/feature/fix text max length and version update 3 0 8 (#50)

* update spaCy up to `3.0.8`;

update spaCy up to `3.0.8`;

* Fix maximum Text of length of nlp

Fix Text of length nlp exceeds maximum of 1000000. Set nlp up to `NLP_EN.max_length = 2000000`

* cleanup

* update and fix Flask

fix `ImportError: cannot import name 'escape' from 'jinja2`:

Jinja is a dependency of Flask and Flask V1.X.X uses the escape module from Jinja, however recently support for the escape module was dropped in newer versions of Jinja.

To fix this issue, simply update to the newer version of Flask V2.X.X in your requirements.txt where Flask no longer uses the escape module from Jinja.

Flask==2.1.2

* set spacy to 3.0.6

* revert spacy to 3.0.8

revert spacy to 3.0.8

* update spaCy up to `3.1.6`

update spaCy up to `3.1.6`

* Set Flask to 2.0.3

Set Flask to 2.0.3

* Set Flask==1.1.2

Set Flask==1.1.2

* Set jinja2<3.1.0

Set jinja2<3.1.0

* Set itsdangerous==2.0.1

Set itsdangerous==2.0.1

* Cleanup

Cleanup

* Set Werkzeug < 2.0.0

Set Werkzeug < 2.0.0

* Set spacy to 3.0.8

Set spacy to 3.0.8

* Set spacy to 3.0.6

Set spacy to 3.0.6

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Set NLP_EN.max_length = 5000000

Set NLP_EN.max_length = 5000000

* Set keepalive_timeout   1550

Set keepalive_timeout   1550

* add big test file for en

add big test file for en

* Set keepalive_timeout   1050

Set keepalive_timeout   1050

* Update to v3.3.2

Update to v3.3.2

* Fix UkrVectōrēs app website address

Fix UkrVectōrēs app website address to https://konspekt.ai-service.pp.ua

* Create LICENSE

* add important note about server avaliability

* add important note

* Bug fixes of deployment process

### 🔴 Bug fixes

- updated up to python:3.7.17-slim-bookworm base docker image;
- fixes wine installation/setup on Debian 12 Bookworm.

### 👥 Contributors

@malakhovks

* Update project description

## v3.3.4: Update project description

### 📚 Docs

- updated project description.

* fix python dev

fix python dev

* fix version and info size

fix version and info size